[[constraint]]
  branch = "master"
  name = "github.com/facebookgo/grace"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.2"

[[constraint]]
  branch = "master"
  name = "github.com/patrickdappollonio/env"

[prune]
  go-tests = true
  unused-packages = true
